unstable_features = true
edition = "2021"
use_field_init_shorthand = true
combine_control_expr = false
control_brace_style = "ClosingNextLine"
fn_single_line = true
format_strings = true
match_block_trailing_comma = true
trailing_comma = "Never"
imports_granularity="Crate"
space_before_colon = true
wrap_comments = true
